# Generated by Django 5.0.6 on 2025-10-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_tags_advice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advice',
            options={'ordering': ('-created_at',), 'verbose_name': 'Совет', 'verbose_name_plural': 'Советы'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at',), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
